[package]
name = "ras"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.24.1"
image = "0.23"

[dev-dependencies]
macroquad = "0.3.26"

